/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DefineEmitsChildren: typeof import('./src/components/DefineEmitsChildren.vue')['default']
    DefineExposeChildren: typeof import('./src/components/DefineExposeChildren.vue')['default']
    DefinePropsChildren: typeof import('./src/components/DefinePropsChildren.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NMenu: typeof import('naive-ui')['NMenu']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
